extends RefCounted
## Named rubric Scenario recipes for revision 1. Dev-only data; store exports
## exclude this tree. ScenarioReference.CATALOGUE is the id → revision contract
## the Console already iterates. Recipes use only OVERRIDE_KEYS.

const SEED: int = 18501

const ENTRIES: Array[Dictionary] = [
	{"id": "title-continue", "revision": 1,
		"description": "A live pilgrimage checkpoint the title Continue action would resume.",
		"seed": SEED, "overrides": {"act": 0, "gold": 40, "add_cards": ["cleave"]}},
	{"id": "act-1-map-start", "revision": 1,
		"description": "Act I map with the lantern unseated at the first waystones.",
		"seed": SEED, "overrides": {"act": 0}},
	{"id": "act-1-map-branch", "revision": 1,
		"description": "Act I seated at a mid-journey fork with two onward roads.",
		"seed": SEED, "overrides": {"act": 0, "node": "4,0"}},
	{"id": "act-1-map-terminus", "revision": 1,
		"description": "Act I seated on the terminus boss waystone.",
		"seed": SEED, "overrides": {"act": 0, "node": "14,3"}},
	{"id": "act-2-map-start", "revision": 1,
		"description": "Act II map with the lantern unseated at the first waystones.",
		"seed": SEED, "overrides": {"act": 1}},
	{"id": "act-2-map-branch", "revision": 1,
		"description": "Act II seated at a mid-journey fork with two onward roads.",
		"seed": SEED, "overrides": {"act": 1, "node": "10,3"}},
	{"id": "act-2-map-terminus", "revision": 1,
		"description": "Act II seated on the terminus boss waystone.",
		"seed": SEED, "overrides": {"act": 1, "node": "14,3"}},
	{"id": "act-3-map-start", "revision": 1,
		"description": "Act III map with the lantern unseated at the first waystones.",
		"seed": SEED, "overrides": {"act": 2}},
	{"id": "act-3-map-branch", "revision": 1,
		"description": "Act III seated at a mid-journey fork with two onward roads.",
		"seed": SEED, "overrides": {"act": 2, "node": "4,6"}},
	{"id": "act-3-map-terminus", "revision": 1,
		"description": "Act III seated on the terminus boss waystone.",
		"seed": SEED, "overrides": {"act": 2, "node": "14,3"}},
	{"id": "act-4-map-start", "revision": 1,
		"description": "Act IV map with the lantern unseated at the first waystones.",
		"seed": SEED, "overrides": {"act": 3, "shards": 6}},
	{"id": "act-4-map-branch", "revision": 1,
		"description": "Act IV seated at a mid-journey fork with two onward roads.",
		"seed": SEED, "overrides": {"act": 3, "shards": 6, "node": "4,6"}},
	{"id": "combat-normal", "revision": 1,
		"description": "A normal two-enemy fight on an Act I monster waystone.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "1,2", "kind": "monster",
			"enemies": ["sporeling", "duskfang"]}},
	{"id": "combat-elite", "revision": 1,
		"description": "An elite fight against the Act I Gravewarden.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "6,3", "kind": "elite", "enemies": ["gravewarden"]}},
	{"id": "combat-boss", "revision": 1,
		"description": "The Act I Rootheart boss fight.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "14,3", "kind": "boss", "enemies": ["rootheart"]}},
	{"id": "combat-low-hp", "revision": 1,
		"description": "A high-load Act III fight at eight HP.",
		"seed": SEED, "overrides": {
			"act": 2, "node": "0,6", "kind": "monster", "hp": 8,
			"enemies": ["voidWisp", "obsidianGolem", "starCultist"]}},
	{"id": "shop-stocked", "revision": 1,
		"description": "A fully stocked stall with gold enough to buy anything.",
		"seed": SEED, "overrides": {"act": 0, "node": "9,3", "gold": 999}},
	{"id": "shop-insufficient-funds", "revision": 1,
		"description": "A stocked stall with an empty purse.",
		"seed": SEED, "overrides": {"act": 0, "node": "9,3", "gold": 0}},
	{"id": "rest", "revision": 1,
		"description": "The rest waystone immediately before the Act I terminus.",
		"seed": SEED, "overrides": {"act": 0, "node": "13,1"}},
	{"id": "event", "revision": 1,
		"description": "An event waystone with its choices still unpicked.",
		"seed": SEED, "overrides": {"act": 0, "node": "11,0"}},
	{"id": "treasure", "revision": 1,
		"description": "A closed treasure chest on the Act I relic row.",
		"seed": SEED, "overrides": {"act": 0, "node": "8,0"}},
	{"id": "vigil", "revision": 1,
		"description": "The Vigil rose with all six panes lit (synthetic fixture; no quest memories). Window-body tap replays the unsealing.",
		"seed": SEED, "overrides": {"shards": 6}},
	{"id": "unsealing-replay", "revision": 1,
		"description": "Six-pane Vigil; Rose Window replay stages the sixth-pane lighting and the one-queue mirror. pending_scene is not an OVERRIDE_KEY.",
		"seed": SEED, "overrides": {"shards": 6}},
	{"id": "combat-unwalked-self", "revision": 1,
		"description": "Act IV tracer: one silent counterfactual self on an Act III monster waystone.",
		"seed": SEED, "overrides": {
			"act": 2, "node": "0,6", "kind": "monster",
			"enemies": ["unwalkedSelf"]}},
	{"id": "combat-uncrossed-self", "revision": 1,
		"description": "Act IV Slice 2: one silent II-prime self on an Act II monster waystone.",
		"seed": SEED, "overrides": {
			"act": 1, "node": "0,6", "kind": "monster",
			"enemies": ["uncrossedSelf"]}},
	{"id": "combat-unopened-self", "revision": 1,
		"description": "Act IV multiplied self: one silent threshold-prime self on an Act I monster waystone.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "0,6", "kind": "monster",
			"enemies": ["unopenedSelf"]}},
	{"id": "combat-eternal-keeper", "revision": 1,
		"description": "Act IV Slice 3: Eternal Keeper boss; a lethal blow hands off instead of dying.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "14,3", "kind": "boss",
			"enemies": ["eternalKeeper"]}},
	{"id": "combat-unlit-self", "revision": 1,
		"description": "Act IV multiplied self: one silent I-prime self on an Act I monster waystone.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "1,2", "kind": "monster",
			"enemies": ["unlitSelf"]}},
	{"id": "combat-unsunk-self", "revision": 1,
		"description": "Act IV first elite: one silent II-prime self on an Act II combat waystone.",
		"seed": SEED, "overrides": {
			"act": 1, "node": "0,6", "kind": "elite",
			"enemies": ["unsunkSelf"]}},
	{"id": "combat-uncarved-self", "revision": 1,
		"description": "Act IV second elite: one silent threshold-prime self on an Act I elite waystone.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "6,3", "kind": "elite",
			"enemies": ["uncarvedSelf"]}},
	{"id": "combat-unobsidian-self", "revision": 1,
		"description": "Act IV multiplied self: one silent III-prime self on an Act III monster waystone.",
		"seed": SEED, "overrides": {
			"act": 2, "node": "0,6", "kind": "monster",
			"enemies": ["unobsidianSelf"]}},
	{"id": "combat-unwooded-self", "revision": 1,
		"description": "Act IV last normal: one silent I-prime self on an Act I monster waystone.",
		"seed": SEED, "overrides": {
			"act": 0, "node": "1,2", "kind": "monster",
			"enemies": ["unwoodedSelf"]}},
	{"id": "act-4-map-rest", "revision": 1,
		"description": "Act IV seated on the rest waystone before the terminus.",
		"seed": SEED, "overrides": {"act": 3, "shards": 6, "node": "n3"}},
	{"id": "act-4-map-terminus", "revision": 1,
		"description": "Act IV seated on the Eternal Keeper waystone.",
		"seed": SEED, "overrides": {"act": 3, "shards": 6, "node": "n4"}},
	{"id": "combat-act4-threshold-prime", "revision": 1,
		"description": "Act IV threshold-prime monster: the landed unopened self on the authored line.",
		"seed": SEED, "overrides": {
			"act": 3, "shards": 6, "node": "n0", "kind": "monster",
			"enemies": ["unopenedSelf"]}},
	{"id": "combat-act4-iii-prime", "revision": 1,
		"description": "Act IV III-prime monster: the landed unwalked self on the authored line.",
		"seed": SEED, "overrides": {
			"act": 3, "shards": 6, "node": "n1", "kind": "monster",
			"enemies": ["unwalkedSelf"]}},
	{"id": "combat-act4-ii-prime", "revision": 1,
		"description": "Act IV II-prime elite: both axes on the authored line.",
		"seed": SEED, "overrides": {
			"act": 3, "shards": 6, "node": "n2", "kind": "elite",
			"enemies": ["uncrossedSelf", "unsunkSelf"]}},
	{"id": "combat-act4-boss", "revision": 1,
		"description": "Act IV hearth-prime boss: the Eternal Keeper on the authored line.",
		"seed": SEED, "overrides": {
			"act": 3, "shards": 6, "node": "n4", "kind": "boss",
			"enemies": ["eternalKeeper"]}},
]

const UNSUPPORTED: Array[Dictionary] = [
	{"id": "title-fresh",
		"reason": "An empty title is Clear Development profile, not a constructed run."},
	{"id": "transition",
		"reason": "The lantern-band ceremony is a route leaf, not a durable checkpoint."},
	{"id": "reward-card",
		"reason": "pending_reward is not an OVERRIDE_KEY."},
	{"id": "reward-relic",
		"reason": "pending_reward is not an OVERRIDE_KEY."},
	{"id": "reward-potion",
		"reason": "pending_reward is not an OVERRIDE_KEY."},
	{"id": "shop-part-sold",
		"reason": "shopStock sold flags are not OVERRIDE_KEYS."},
	{"id": "event-choice-card",
		"reason": "eventNode/eventPending are not OVERRIDE_KEYS."},
	{"id": "event-choice-remove",
		"reason": "eventNode/eventPending are not OVERRIDE_KEYS."},
	{"id": "event-choice-duplicate",
		"reason": "eventNode/eventPending are not OVERRIDE_KEYS."},
	{"id": "event-choice-upgrade",
		"reason": "eventNode/eventPending are not OVERRIDE_KEYS."},
	{"id": "run-menu",
		"reason": "Run-menu open is presentation chrome, not a run checkpoint."},
	{"id": "deck-overlay",
		"reason": "Deck inspector open is presentation chrome, not a run checkpoint."},
	{"id": "settings-overlay",
		"reason": "Settings open is presentation chrome, not a run checkpoint."},
	{"id": "defeat",
		"reason": "pending_run_end is not an OVERRIDE_KEY."},
	{"id": "act-victory",
		"reason": "pending_run_end and the boss-relic beat are not OVERRIDE_KEYS."},
	{"id": "dawn",
		"reason": "pending_dawn is not an OVERRIDE_KEY."},
	{"id": "opening",
		"reason": "pending_scene is not an OVERRIDE_KEY."},
	{"id": "opening-resume",
		"reason": "pending_scene is not an OVERRIDE_KEY."},
	{"id": "l0-hearth-plant",
		"reason": "Ambient departure staging is not a durable checkpoint."},
	{"id": "unsealing",
		"reason": "Vigil pending_scene is not an OVERRIDE_KEY."},
	{"id": "unsealing-resume",
		"reason": "Vigil pending_scene is not an OVERRIDE_KEY."},
	{"id": "unsealing-short",
		"reason": "The repeat door-crossing beat needs an Act IV to cross into (#312)."},
	{"id": "onboarding",
		"reason": "Onboarding Scenarios graduate with the guided-first-run feature."},
]


static func recipe_for(id: String) -> Dictionary:
	for row: Dictionary in ENTRIES:
		if str(row.get("id", "")) == id:
			return row
	return {}
