#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

TEMPLATES_DIR="$HOME/Library/Application Support/Godot/export_templates/4.7.1.stable"
KEYSTORE_DIR="$HOME/Library/Application Support/Godot/keystores"
KEYSTORE="$KEYSTORE_DIR/glassvow-upload.keystore"
KEY_ALIAS="glassvow-upload"
UPLOAD_PW=""

banner "Glassvow — store accounts + signing pipeline"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight — toolchain check"
[[ -f export_presets.cfg ]] || { warn "run this from the glassvow repo root"; exit 1; }
GODOT_V=$(godot --version 2>/dev/null || true)
[[ "$GODOT_V" == 4.7.1.stable* ]] || { warn "godot --version says '$GODOT_V', need 4.7.1.stable"; exit 1; }
say "Godot 4.7.1.stable ✓"
for f in ios.zip android_source.zip android_debug.apk android_release.apk; do
  [[ -f "$TEMPLATES_DIR/$f" ]] || { warn "missing $TEMPLATES_DIR/$f — reinstall 4.7.1 export templates"; exit 1; }
done
say "iOS + Android export templates ✓"
xcodebuild -version | head -1
[[ -d "$HOME/Library/Android/sdk/platforms/android-36" ]] || warn "Android SDK platform 36 missing (Play requires target API 36 from 2026-08-31)"
# Gradle 8.11 (Godot 4.7 template) chokes on JDK >23 — docs pin OpenJDK 17.
JDK_PATH=$(grep 'export/android/java_sdk_path' "$HOME/Library/Application Support/Godot/editor_settings-4.7.tres" | cut -d'"' -f2)
if "$JDK_PATH/bin/java" -version 2>&1 | grep -q 'version "17'; then
  say "JDK 17 at $JDK_PATH ✓"
else
  warn "Godot's java_sdk_path ($JDK_PATH) is not JDK 17 — gradle will fail."
  warn "Expected /Users/jamesto/.local/share/jdk-17/Contents/Home (Temurin 17)."
  exit 1
fi
if [[ ! -f android/.build_version ]]; then
  say "installing Android gradle build template (android/build)..."
  mkdir -p android/build
  unzip -q -o "$TEMPLATES_DIR/android_source.zip" -d android/build
  echo "4.7.1.stable" > android/.build_version
  touch android/build/.gdignore
fi
say "Android gradle build template ✓"
mkdir -p build/android build/ios
pause

# ── Stage 2: Apple Developer Program ──────────────────────────────────────
stage "Apple Developer Program (US\$99/yr)"
say "Individual enrollment shows your personal name on the store;"
say "organization enrollment needs a D-U-N-S number + domain website/email."
open_url "https://developer.apple.com/programs/enroll/"
step "Enroll (or confirm the membership is active) and pay the US\$99 fee."
step "In App Store Connect → Agreements, accept the Paid Applications agreement."
note "EU DSA: you'll declare trader status at first app submission — a paid game"
note "is in practice a trader; address/phone/email get verified and shown in the EU."
pause "Done? Press Enter."
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Under Membership details, copy the 10-character Team ID."
ask APPLE_TEAM_ID "Paste the Team ID:"
sed -i '' "s|^application/app_store_team_id=.*|application/app_store_team_id=\"$APPLE_TEAM_ID\"|" export_presets.cfg
say "✓ wrote Team ID into export_presets.cfg (iOS preset) — commit this change"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── Stage 3: Xcode signing bootstrap ──────────────────────────────────────
stage "Xcode — sign in your Apple ID"
step "Open Xcode → Settings… → Accounts → '+' → add the Apple ID you enrolled with."
say "Automatic signing will create the Apple Distribution certificate and"
say "provisioning profile on your first archive — nothing to make by hand."
pause "Signed in? Press Enter."

# ── Stage 4: Google Play Console ──────────────────────────────────────────
stage "Google Play Console (US\$25 one-time)"
SKIP_PLAY=0
say "Android is deferred: it ships after the iOS release, before desktop/Steam"
say "(map #156 decision, 2026-08-13). Stages 4-6 are the Google side."
if ! confirm "Set up the Google Play side now anyway?"; then
  SKIP_PLAY=1
fi
if [[ "$SKIP_PLAY" == 0 ]]; then
open_url "https://play.google.com/console/signup"
step "Register a developer account and pay the US\$25 fee."
say "Personal vs organization matters:"
note "  personal (created after 2023-11): every new app must first run a closed"
note "  test with 12+ testers for 14 days before production access"
note "  organization: no 12-tester gate, but needs a payments profile + D-U-N-S"
step "Complete identity verification (ID document) and, on a personal account,"
step "verify an Android device via the Play Console app."
step "Set up the payments profile (required to sell a paid app)."
note "EEA: identity verification under DSA/DMA is part of the same flow."
pause "Account verified? Press Enter."
fi

# ── Stage 5: upload keystore ──────────────────────────────────────────────
stage "Android upload keystore"
if [[ "$SKIP_PLAY" == 1 ]]; then
  note "skipped — Android deferred; re-run this wizard when that phase starts"
else
mkdir -p "$KEYSTORE_DIR"
if [[ -f "$KEYSTORE" ]]; then
  say "keystore already exists: $KEYSTORE — keeping it."
else
  say "Generating the Play upload key (RSA 4096, valid 10,000 days)."
  say "Godot quirk: keystore password and key password must be IDENTICAL;"
  say "stick to letters and digits only."
  while true; do
    ask_secret UPLOAD_PW "Choose the keystore password:"
    ask_secret UPLOAD_PW2 "Repeat it:"
    [[ -n "$UPLOAD_PW" && "$UPLOAD_PW" == "$UPLOAD_PW2" ]] && break
    warn "empty or mismatched — try again"
  done
  ask KS_CN "Name for the key's certificate (CN) [default fol2]:"
  keytool -genkeypair -v -keystore "$KEYSTORE" -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10000 \
    -storepass "$UPLOAD_PW" -keypass "$UPLOAD_PW" \
    -dname "CN=${KS_CN:-fol2}"
  say "✓ created $KEYSTORE"
fi
warn "Back up the keystore file AND its password in your password manager now."
note "Play App Signing holds the real app key; this is only the upload key —"
note "losable but painful (reset via a Play Console help form)."
pause
fi

# ── Stage 6: signed Android release build (AAB) ───────────────────────────
stage "Signed Android release build"
if [[ "$SKIP_PLAY" == 1 ]]; then
  note "skipped — Android deferred; re-run this wizard when that phase starts"
else
if [[ -z "$UPLOAD_PW" ]]; then
  ask_secret UPLOAD_PW "Keystore password for $KEYSTORE:"
fi
say "Exporting release AAB (target API 36, arm64, signed with the upload key)..."
GODOT_ANDROID_KEYSTORE_RELEASE_PATH="$KEYSTORE" \
GODOT_ANDROID_KEYSTORE_RELEASE_USER="$KEY_ALIAS" \
GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD="$UPLOAD_PW" \
  godot --headless --export-release "Android (Play AAB)" build/android/glassvow.aab
jarsigner -verify build/android/glassvow.aab
say "✓ build/android/glassvow.aab exported and signature verified"
note "Play's upload screen re-checks the target API level — it must say 36."
note "For future uploads: bump version/code in the Android preset every time."
note "Optional: set the same keystore in Godot's editor (Export → Android →"
note "Keystore); Godot stores it in export_credentials.cfg, which is gitignored."
pause
fi

# ── Stage 7: iOS Xcode project + signed archive ───────────────────────────
stage "iOS — export, archive, distribution-sign"
say "Exporting the Xcode project (Godot signs nothing; Xcode does)..."
godot --headless --export-release "iOS" build/ios/glassvow.ipa
say "✓ Xcode project at build/ios/"
say "Archiving (development signing; distribution happens at export)..."
xcodebuild -project build/ios/glassvow.xcodeproj -scheme glassvow \
  -destination "generic/platform=iOS" archive \
  -archivePath build/ios/glassvow.xcarchive \
  -allowProvisioningUpdates CODE_SIGN_IDENTITY="Apple Development" \
  | tail -2
say "Re-signing with Apple Distribution and exporting the .ipa..."
if xcodebuild -exportArchive -archivePath build/ios/glassvow.xcarchive \
     -exportPath build/ios/export \
     -exportOptionsPlist scripts/ios_export_options.plist \
     -allowProvisioningUpdates; then
  say "✓ signed .ipa at build/ios/export/"
else
  warn "exportArchive failed (usually 'No Accounts' — the CLI can't reach"
  warn "Xcode's Apple ID session). Finish this one step in the Xcode UI:"
  open_url "$(pwd)/build/ios/glassvow.xcarchive"
  step "Organizer opens with the archive → Distribute App → App Store"
  step "Connect → Export (not Upload) — that writes the signed .ipa."
  note "For fully headless releases later: create an App Store Connect API"
  note "key and pass -authenticationKeyPath/-authenticationKeyID/"
  note "-authenticationKeyIssuerID to xcodebuild."
fi
say "A signed .ipa on disk is the release-candidate proof this pipeline"
say "works end to end. Uploading waits for the store-presence work."
pause "Signed .ipa in hand? Press Enter."

finish
warn "Still ahead (other tickets): store listings/assets, privacy declarations,"
warn "age ratings, DSA trader declaration at first submission."
