"""COMPAT-2 generated-input slots, validation and immutable-copy promotion.

The SAME private root remains read-only; only predeclared generated slots are
bind-mounted writable. Empty mountpoints are layout, never imported metadata.
Directory-slot contents are provisional until their exact inventory validates.
No engine is invoked here, no original source is made writable, no account is
created, and no hash or recipe is an authentication substitute.
"""
from pathlib import Path, PurePosixPath
import os
import re
import stat
import dd1_reservations as r
import dd1_prep_view as view


def path_name(name):
    r.need(isinstance(name, str) and 0 < len(name) <= 300 and
           re.fullmatch(r"[A-Za-z0-9_.\-/]+", name) is not None and
           str(PurePosixPath(name)) == name and not name.startswith("/") and
           all(p not in ("", ".", "..", ".git", ".env", ".ssh", "ACCOUNT.json")
               for p in name.split("/")), "invalid generated path")
    return name


def validate_recipe(unit, source):
    recipe = unit.get("preparation")
    if recipe is None:
        return None
    r.need(unit.get("stage") == "preparation" and unit.get("sealed_input") is None,
           "preparation stage/lineage mismatch")
    required = {"schema", "source_head", "source_manifest_sha256", "engine_sha256", "slots"}
    amended = view.selected(recipe)
    if amended:
        required |= {"view", "producer"}
    r.need(isinstance(recipe, dict) and set(recipe) == required and
           recipe["schema"] in ("DD1-PREPARATION-2", view.SCHEMA), "preparation recipe schema")
    r.need(len(r.encode(recipe)) <= 131072, "preparation recipe size bound")
    r.need(recipe["source_head"] == unit["overlay_head"] and
           recipe["source_manifest_sha256"] == r.digest(r.encode(unit["source_files"])),
           "preparation source lineage")
    entry = unit["linux"]["runtime"][unit["argv"][0]]
    r.need(recipe["engine_sha256"] == entry["sha256"], "preparation engine lineage")
    slots = recipe["slots"]
    r.need(isinstance(slots, list) and 0 < len(slots) <= 128, "bounded preparation slots")
    original = {s[6:] for s in source}
    roots, outputs = [], set()
    for slot in slots:
        r.need(isinstance(slot, dict), "slot schema")
        schema = set(slot) - ({"seed"} if amended else set())
        r.need(schema in ({"path", "kind", "files"}, {"path", "kind", "files", "temporary_files"}), "slot schema")
        name = path_name(slot["path"])
        r.need(slot["kind"] in ("file", "directory"), "slot kind")
        overlap = {name} if amended and "seed" in slot and name in original else set()
        r.need(not any(name == p or name.startswith(p + "/") or p.startswith(name + "/")
                       for p in (original - overlap) | set(roots)), "slot shadows/aliases frozen input")
        r.need("seed" not in slot or overlap == {name}, "seed must name an existing immutable original")
        r.need((slot["kind"] == "directory" and name == ".godot") or
               (slot["kind"] == "file" and name.endswith((".import", ".uid"))),
               "not a generated import/UID/cache slot")
        temporary = slot.get("temporary_files", [])
        r.need(isinstance(temporary, list) and len(temporary) <= 4096 and
               (slot["kind"] == "directory" or not temporary) and
               len(set(temporary)) == len(temporary), "invalid temporary generated inventory")
        for relative in temporary:
            path_name(relative)
        roots.append(name)
        files = slot["files"]
        r.need(isinstance(files, dict) and files and len(files) <= 4096, "generated inventory")
        for relative, limits in files.items():
            r.need(slot["kind"] == "directory" or relative == "", "file slot inventory")
            full = name + "/" + path_name(relative) if slot["kind"] == "directory" else name
            r.need(full not in outputs and isinstance(limits, dict) and
                   set(limits) == {"min_bytes", "max_bytes"}, "duplicate/generated limit schema")
            r.need(0 < r.natural(limits["min_bytes"], "minimum") <=
                   r.natural(limits["max_bytes"], "maximum") <= (1 << 30), "generated byte range")
            outputs.add(full)
        r.need(not set(temporary) & set(files), "temporary/output overlap")
        paths = set(files) | set(temporary)
        if slot["kind"] == "directory":
            r.need(not any(str(parent) in paths for n in paths
                           for parent in PurePosixPath(n).parents if str(parent) != "."),
                   "generated file/directory collision")
            r.need(len(paths) <= 4096, "generated paths bound")
    r.need(len(outputs) <= 4096, "generated file count")
    if amended:
        view.validate(unit, source)
    return recipe


def reserve_copy_bytes(recipe, source):
    if recipe is None:
        return 0
    generated = sum(v["max_bytes"] + 16384 for s in recipe["slots"] for v in s["files"].values())
    # Charge the complete predeclared layout too: temporary paths can require
    # directories/watch entries even when they leave no final output file.
    layout = set()
    for index, slot in enumerate(recipe["slots"]):
        for name in (*slot["files"], *slot.get("temporary_files", [])):
            full = str(index) + ("/" + name if name else "")
            layout.add(full)
            layout.update(str(p) for p in PurePosixPath(full).parents if str(p) != ".")
    # Seed backing initialization plus an immutable original archive at sealing.
    extra = 0
    if view.selected(recipe):
        archives = (view.PROJECT, *view.seeded(recipe))
        extra = sum(len(source[n]) + 16384 for n in archives)
        extra += sum(len(source[n]) + 16384 for n in view.seeded(recipe))
        extra += 2 * len(r.encode(recipe)) + 16384
    # One complete sealed copy, bounded manifest/journal, and layout metadata.
    return extra + (sum(len(b) + 16384 for b in source.values()) + generated +
            524288 + 139264 + 32768 * len(recipe["slots"]) + 16384 * len(layout))


def create_slots(root, capture, recipe, source=None):
    if recipe is None:
        return
    lines = []
    # Backing parents stay outside /out; the workload sees only bound slots.
    directory = capture.parent / "derived"
    directory.mkdir(mode=0o700)
    for index, slot in enumerate(recipe["slots"]):
        target = root / "source" / slot["path"]
        seed = None
        if view.selected(recipe) and "seed" in slot:
            seed = source["res://" + slot["path"]]
            r.need(_regular(target, len(seed)) == seed, "seeded mountpoint not exact original")
        else:
            r.need(not target.exists() and not target.is_symlink(), "nonfresh generated mountpoint")
        target.parent.mkdir(parents=True, exist_ok=True)
        backing = directory / str(index)
        if slot["kind"] == "directory":
            target.mkdir(); backing.mkdir(mode=0o700)
            # Install watches on every permitted directory BEFORE release. A
            # new unobserved subtree cannot hide a create/write/delete cycle.
            for relative in (*slot["files"], *slot.get("temporary_files", [])):
                (backing / relative).parent.mkdir(parents=True, exist_ok=True)
        else:
            if seed is None:
                target.touch(exist_ok=False)
            with backing.open("xb") as stream:
                if seed is not None:
                    stream.write(seed)
                stream.flush(); os.fsync(stream.fileno())
            backing.chmod(0o600)
            if seed is not None:
                r.need(_regular(backing, len(seed)) == seed, "seed backing readback")
        lines.append(f"{slot['kind'][0]} source/{slot['path']} {index}\n")
    with (root / "dd1-preparation.layout").open("x") as f:
        f.writelines(lines); f.flush(); os.fsync(f.fileno())


def _regular(path, maximum):
    r.need(path.absolute() == path.resolve() and not path.is_symlink(), "derived/sealed path alias")
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC | os.O_NONBLOCK)
    with os.fdopen(fd, "rb") as f:
        st = os.fstat(f.fileno())
        r.need(stat.S_ISREG(st.st_mode) and st.st_nlink == 1 and st.st_size <= maximum,
               "derived/sealed nonregular, hardlink or oversized output")
        data = f.read(maximum + 1)
        r.need(len(data) == st.st_size, "changing derived output")
        return data


def _inventory(root):
    files, directories, stack, seen = set(), set(), [root], 0
    while stack:
        for p in stack.pop().iterdir():
            seen += 1
            r.need(seen <= 8192, "derived inventory bound")
            r.need(not p.is_symlink(), "derived symlink")
            if p.is_dir():
                r.need(p.absolute() == p.resolve(), "derived directory alias")
                directories.add(p.relative_to(root).as_posix())
                stack.append(p)
            else:
                files.add(p.relative_to(root).as_posix())
            r.need(len(files) + len(stack) <= 8192, "derived inventory bound")
    parents = {str(parent) for name in files for parent in PurePosixPath(name).parents
               if str(parent) != "."}
    r.need(directories <= parents, "unexpected empty generated directory")
    return files


def seal(unit, pinned, output, cleanup, task_ok):
    recipe = pinned.get("preparation")
    if recipe is None:
        return None
    r.need(cleanup and task_ok, "failed/interrupted preparation cannot promote")
    # All workload threads have been reaped. Mutable preparation paths are never
    # a source for a subsequent child; validated bytes are copied to a NEW tree.
    derived = {}
    for index, slot in enumerate(recipe["slots"]):
        backing = output / "derived" / str(index)
        if slot["kind"] == "directory":
            r.need(backing.is_dir() and not backing.is_symlink(), "missing generated directory")
            r.need(_inventory(backing) == set(slot["files"]), "stale/missing/unexpected generated inventory")
        for relative, limits in slot["files"].items():
            path = backing / relative if relative else backing
            raw = _regular(path, limits["max_bytes"])
            r.need(len(raw) >= limits["min_bytes"], "missing/empty generated output")
            name = slot["path"] + "/" + relative if relative else slot["path"]
            derived["res://" + name] = raw
    for index, slot in enumerate(recipe["slots"]):
        if slot["kind"] == "directory":
            backing = output / "derived" / str(index)
            r.need(all(not (backing / name).exists() and not (backing / name).is_symlink()
                       for name in slot.get("temporary_files", [])), "stale temporary generated output")
    original = pinned["source"]
    combined = {**original, **derived}
    fields, archives = {}, {}
    if view.selected(recipe):
        r.need(set(original) & set(derived) == set(view.seeded(recipe)), "undeclared seeded overwrite")
        fields, archives = view.seal_fields(unit, pinned, derived, output)
    else:
        r.need(len(combined) == len(original) + len(derived), "derived source overwrite")
    dest = output / "sealed"
    dest.mkdir(mode=0o700)
    payload = dest / "payload"; payload.mkdir(mode=0o700)
    actual = 0
    for name, raw in combined.items():
        p = payload / name[6:]; p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("xb") as f:
            f.write(raw); f.flush(); os.fsync(f.fileno())
        p.chmod(0o400)
        r.need(_regular(p, len(raw)) == raw, "sealed copy readback")
        actual += len(raw) + 16384
    for name, raw in archives.items():
        p = dest / "originals" / name[6:]; p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("xb") as f:
            f.write(raw); f.flush(); os.fsync(f.fileno())
        p.chmod(0o400)
        r.need(_regular(p, len(raw)) == raw, "sealed original archive readback")
        actual += len(raw) + 16384
    receipt = dict(schema="DD1-SEALED-PREPARATION-3" if fields else "DD1-SEALED-PREPARATION-2", unit_id=unit["unit_id"],
        source_head=unit["overlay_head"], source_manifest_sha256=r.digest(r.encode(unit["source_files"])),
        engine_sha256=recipe["engine_sha256"], runtime_sha256=r.digest(r.encode(unit["linux"]["runtime"])),
        recipe_sha256=r.digest(r.encode(recipe)), demand_sha256=r.digest(r.encode(unit)),
        before_account_sha256=unit["account_sha256"], generated={k: r.digest(v) for k, v in derived.items()},
        files={k: {"sha256": r.digest(v), "bytes": len(v)} for k, v in combined.items()},
        task_ok=True, cleanup_confirmed=True, protection="READ_ONLY_ROOT_EXACT_GENERATED_SLOTS",
        copied_raw_bytes=actual)
    receipt.update(fields)
    raw = r.encode(receipt)
    r.need(len(raw) <= 524288, "sealed receipt byte bound")
    r.need(actual + len(raw) + 16384 <= pinned["promotion_raw"], "sealed copy exceeds pre-reserved raw")
    with (dest / "SEAL.json").open("xb") as f:
        f.write(raw); f.flush(); os.fsync(f.fileno())
    (dest / "SEAL.json").chmod(0o400)
    # In-host filesystem modes are defense in depth. Subsequent execution uses
    # validated copied bytes in a fresh KERNEL read-only root, not these modes.
    for p in sorted(dest.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        if p.is_dir(): p.chmod(0o500)
    payload.chmod(0o500); dest.chmod(0o500)
    return {"sha256": r.digest(raw), "receipt_path": str(dest / "SEAL.json"),
            "unit_id": unit["unit_id"], "copied_raw_bytes": actual + len(raw)}


def load_sealed(unit, account):
    binding = unit.get("sealed_input")
    if binding is None:
        return {}
    r.need(unit.get("stage") in ("parse", "fixture") and not unit.get("preparation"), "invalid sealed stage")
    r.need(isinstance(binding, dict) and set(binding) == {"unit_id", "receipt_path", "sha256"}, "sealed binding schema")
    rows = [x for x in account["recovery"].get("unit_reservations_v2", []) if x["unit_id"] == binding["unit_id"]]
    r.need(len(rows) == 1 and rows[0]["state"] == "COMPLETE", "missing/failed preparation reservation")
    observations = rows[0].get("observations") or {}
    r.need(observations.get("success") is True and observations.get("cleanup_confirmed") is True and
           observations.get("sealed_preparation", {}).get("sha256") == binding["sha256"] and
           observations["sealed_preparation"]["receipt_path"] == binding["receipt_path"], "unbound preparation receipt")
    path = Path(binding["receipt_path"])
    raw = _regular(path, 524288)
    r.need(path.name == "SEAL.json" and r.digest(raw) == binding["sha256"], "sealed receipt changed")
    receipt = __import__("json").loads(raw)
    amended = receipt.get("schema") == "DD1-SEALED-PREPARATION-3"
    r.need(receipt["schema"] in ("DD1-SEALED-PREPARATION-2", "DD1-SEALED-PREPARATION-3") and receipt["task_ok"] is True and
           receipt["cleanup_confirmed"] is True and receipt["unit_id"] == binding["unit_id"] and
           receipt["demand_sha256"] == rows[0]["demand_sha256"] and
           receipt["before_account_sha256"] == rows[0]["before_account_sha256"] and
           receipt["source_head"] == unit["overlay_head"] and
           receipt["source_manifest_sha256"] == r.digest(r.encode(unit["source_files"])) and
           receipt["engine_sha256"] == unit["linux"]["runtime"][unit["argv"][0]]["sha256"] and
           receipt["runtime_sha256"] == r.digest(r.encode(unit["linux"]["runtime"])), "sealed engine/source/demand lineage")
    originals = set(unit["source_files"])
    generated_names = set(receipt["generated"])
    allowed = set(view.seeded(receipt["recipe"])) if amended else set()
    r.need((originals & generated_names) == allowed and
           set(receipt["files"]) == originals | generated_names,
           "incomplete or overlapping sealed input inventory")
    payload = path.parent / "payload"
    r.need(_inventory(payload) == {n[6:] for n in receipt["files"]}, "sealed snapshot inventory changed")
    data, original_bytes = {}, {}
    for name, expected in receipt["files"].items():
        r.need(name.startswith("res://"), "sealed name")
        p = payload / path_name(name[6:]); b = _regular(p, expected["bytes"])
        r.need(len(b) == expected["bytes"] and r.digest(b) == expected["sha256"], "sealed snapshot corruption")
        if name in receipt["generated"]:
            r.need(r.digest(b) == receipt["generated"][name], "cache splicing")
            data[name] = b
        else:
            r.need(unit["source_files"].get(name) == expected["sha256"], "sealed original mismatch")
            original_bytes[name] = b
    if amended:
        archive = path.parent / "originals"
        wanted = {view.PROJECT, *allowed}
        r.need(set(receipt["original_archive"]) == wanted and
               _inventory(archive) == {n[6:] for n in wanted}, "sealed original archive inventory")
        for name, spec in receipt["original_archive"].items():
            b = _regular(archive / path_name(name[6:]), spec["bytes"])
            r.need(len(b) == spec["bytes"] and r.digest(b) == spec["sha256"] == unit["source_files"].get(name),
                   "sealed original archive corruption")
            r.need(name != view.PROJECT or original_bytes.get(name) == b, "runtime project restoration changed")
            original_bytes[name] = b
        r.need(unit["mode"] == "inert_control" or receipt.get("semantic_scope") == "HOST_QUALIFICATION_REQUIRED",
               "synthetic preparation cannot become native input")
        return view.verify_seal(receipt, unit, original_bytes, data)
    return data
