"""Payload and provenance gate for the reassembled fixed-camera landscape.

Runs from check_map_assets.py. Painted cards are two triangles with runtime
mipmaps; they do not inherit the retired triplanar library's opaque-tile rules.
"""
from __future__ import annotations

import hashlib
import json
import tempfile
from pathlib import Path

from PIL import Image
from map_asset_checks import Finding, check_mesh

PNG_BYTES_MAX = 4 * 1024 * 1024
PACKAGE_BYTES_MAX = 40 * 1024 * 1024
KINDS = {'painted-card', 'terrain', 'mesh'}


def scan(folder: Path, *, rasterise: bool = True) -> tuple[list[Finding], int]:
    manifest = json.loads((folder / 'provenance.json').read_text())
    if not isinstance(manifest, dict) or manifest.get('schema_version') != 1 \
            or not isinstance(manifest.get('assets'), list) or not manifest['assets']:
        raise ValueError('Landscape provenance needs schema 1 and a nonempty asset list')
    found: list[Finding] = []
    declared: set[str] = set()
    total = 0
    for row in manifest['assets']:
        if not isinstance(row, dict):
            raise ValueError('Landscape asset record must be an object')
        name = row.get('file')
        kind = row.get('kind')
        if not isinstance(name, str) or Path(name).name != name or name in declared \
                or kind not in KINDS or Path(name).suffix != ('.glb' if kind == 'mesh' else '.png'):
            raise ValueError('Invalid, duplicate or unsupported landscape asset')
        declared.add(name)
        path = folder / name
        if not path.is_file() or path.is_symlink():
            found.append(Finding('landscape', name, 'declared payload is missing or a symlink'))
            continue
        data = path.read_bytes()
        total += len(data)
        if hashlib.sha256(data).hexdigest() != row.get('sha256'):
            found.append(Finding('landscape', name, 'payload does not match its recorded SHA-256'))
        if not all(isinstance(row.get(key), str) and row[key].strip()
                   for key in ('source', 'created_at', 'licence', 'prompt_brief')):
            found.append(Finding('landscape', name, 'source, date, licence or authoring brief is missing'))
        if not path.with_name(name + '.import').is_file():
            found.append(Finding('landscape', name, 'Godot-generated import sidecar is missing'))
        if kind == 'mesh':
            if rasterise:
                found.extend(check_mesh(path, str(path), {
                    'kind': 'kit', 'triangle_max': 2500, 'bytes_max': 192 * 1024}))
            continue
        with Image.open(path) as image:
            if list(image.size) != row.get('dimensions') or max(image.size) > 1536:
                found.append(Finding('landscape', name, 'dimensions differ from provenance or exceed 1536px'))
            if len(data) > PNG_BYTES_MAX:
                found.append(Finding('landscape', name, 'PNG exceeds 4 MiB'))
            if kind == 'terrain' and image.mode != 'RGB':
                found.append(Finding('landscape', name, 'terrain must be opaque RGB'))
            if kind == 'painted-card':
                if image.mode != 'RGBA':
                    found.append(Finding('landscape', name, 'painted card has no real alpha channel'))
                else:
                    histogram = image.getchannel('A').histogram()
                    pixels = image.width * image.height
                    if sum(histogram[:16]) / pixels < .10 or sum(histogram[128:]) / pixels < .10:
                        found.append(Finding('landscape', name, 'card needs both clear margin and visible artwork'))
    present = {path.name for path in folder.iterdir() if path.suffix in {'.png', '.glb'}}
    if present != declared:
        found.append(Finding('landscape', str(folder), f'undeclared or absent payloads: {sorted(present ^ declared)}'))
    if total > PACKAGE_BYTES_MAX:
        found.append(Finding('landscape', str(folder), 'package exceeds 40 MiB'))
    return found, len(present)


def self_test() -> list[str]:
    """A checkerboard without alpha, a changed payload and an unknown file fail."""
    errors = []
    with tempfile.TemporaryDirectory(prefix='landscape-gate-') as directory:
        folder = Path(directory)
        image = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
        image.paste((80, 100, 100, 255), (4, 4, 12, 12))
        path = folder / 'card.png'
        image.save(path)
        # Fixture-only sidecar: production sidecars are generated by Godot.
        (folder / 'card.png.import').write_text('fixture')
        row = {'file': 'card.png', 'kind': 'painted-card', 'dimensions': [16, 16],
               'source': 'fixture', 'created_at': '2026-09-05', 'licence': 'fixture',
               'prompt_brief': 'checker fixture', 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()}
        manifest = folder / 'provenance.json'
        manifest.write_text(json.dumps({'schema_version': 1, 'assets': [row]}))
        if scan(folder, rasterise=False)[0]:
            errors.append('landscape gate rejected its valid transparent fixture')
        image.convert('RGB').save(path)
        findings, _ = scan(folder, rasterise=False)
        if not any('alpha' in item.detail for item in findings) \
                or not any('SHA-256' in item.detail for item in findings):
            errors.append('landscape gate missed opaque replacement or changed payload')
        (folder / 'undeclared.glb').write_bytes(b'not a GLB')
        if not any('undeclared' in item.detail for item in scan(folder, rasterise=False)[0]):
            errors.append('landscape gate missed an undeclared asset')
    return errors
